void main() {
  // Değişkenlerin tanımlanması ve değer ataması
  String ilce = "Beşiktaş";
  String kita = "Avrupa";
  String faks = "0212 123 4567";
  String postaKodu = "34330";
  String instaAdresi = "@muammer_ozer";
  String calistiginBolum = "Yazılım Geliştirme";
  int urunMiktari = 150;
  String musteriSoyadi = "Yılmaz";
  double odemeMiktari = 299.99;
  DateTime dogumTarihi = DateTime(1995, 5, 20);
  double borc = 450.50;
  String medeniHal = "Bekar";
  String videoYorumu = "Harika bir video!";
  double eftMiktari = 1200.75;
  int satilanMiktar = 75;
  String telefonModeli = "iPhone 13";
  String dergiAdi = "Teknoloji Dünyası";
  DateTime basimTarihi = DateTime(2023, 7, 15);
  double zamMiktari = 500.0;
  int daireSayisi = 24;
  double enlem = 41.0082;
  double boylam = 28.9784;
  String yemekAdi = "Lahmacun";
  double urunFiyati = 45.99;
  String sirket = "Özer Yazılım";
  String videoAdi = "Eğitim Videosu";
  Duration muzikSuresi = Duration(minutes: 3, seconds: 45);
  double mekanPuani = 4.7;
  String dosyaAdi = "Rapor.docx";
  String resimFormati = "JPEG";
  String renk = "Mavi";
  String renkKodu = "#0000FF";
  String bilgisayarModeli = "Dell XPS 13";
  double ekranBoyutu = 13.3;
  Duration kullanimSuresi = Duration(hours: 5, minutes: 30);
  double basinc = 1013.25;
  String etkinlikGunu = "Cumartesi";
  DateTime odemeGunu = DateTime(2024, 8, 28);
  DateTime yolculukCikisTarihi = DateTime(2024, 9, 15);
  String mahalleAdi = "Moda";
  String otobusHatti = "34AS";
  Duration kullanilanDakika = Duration(minutes: 300);
  String kargoTakipNo = "TR123456789";
  Duration kuponSuresi = Duration(days: 30);
  String kuponKodu = "INDIRIM20";
  DateTime faturaTarihi = DateTime(2024, 8, 25);
  
  // Değişkenlerin konsola yazdırılması
  print("İlçe: $ilce");
  print("Kıta: $kita");
  print("Faks: $faks");
  print("Posta Kodu: $postaKodu");
  print("Instagram Adresi: $instaAdresi");
  print("Çalıştığın Bölüm: $calistiginBolum");
  print("Ürün Miktarı: $urunMiktari");
  print("Müşteri Soyadı: $musteriSoyadi");
  print("Ödeme Miktarı: $odemeMiktari");
  print("Doğum Tarihi: $dogumTarihi");
  print("Borç: $borc");
  print("Medeni Hal: $medeniHal");
  print("Video Yorumu: $videoYorumu");
  print("EFT Miktarı: $eftMiktari");
  print("Satılan Miktar: $satilanMiktar");
  print("Telefon Modeli: $telefonModeli");
  print("Dergi Adı: $dergiAdi");
  print("Basım Tarihi: $basimTarihi");
  print("Zam Miktarı: $zamMiktari");
  print("Daire Sayısı: $daireSayisi");
  print("Enlem: $enlem");
  print("Boylam: $boylam");
  print("Yemek Adı: $yemekAdi");
  print("Ürün Fiyatı: $urunFiyati");
  print("Şirket: $sirket");
  print("Video Adı: $videoAdi");
  print("Müzik Süresi: ${muzikSuresi.inMinutes}:${muzikSuresi.inSeconds % 60}");
  print("Mekan Puanı: $mekanPuani");
  print("Dosya Adı: $dosyaAdi");
  print("Resim Formatı: $resimFormati");
  print("Renk: $renk");
  print("Renk Kodu: $renkKodu");
  print("Bilgisayar Modeli: $bilgisayarModeli");
  print("Ekran Boyutu: $ekranBoyutu");
  print("Kullanım Süresi: ${kullanimSuresi.inHours} saat ${kullanimSuresi.inMinutes % 60} dakika");
  print("Basınç: $basinc");
  print("Etkinlik Günü: $etkinlikGunu");
  print("Ödeme Günü: $odemeGunu");
  print("Yolculuk Çıkış Tarihi: $yolculukCikisTarihi");
  print("Mahalle Adı: $mahalleAdi");
  print("Otobüs Hattı: $otobusHatti");
  print("Kullanılan Dakika: ${kullanilanDakika.inMinutes} dakika");
  print("Kargo Takip No: $kargoTakipNo");
  print("Kupon Süresi: ${kuponSuresi.inDays} gün");
  print("Kupon Kodu: $kuponKodu");
  print("Fatura Tarihi: $faturaTarihi");
}
